In [26]:
import pandas as pd

df_reports = "/home/public/mkamal/dataset/filtered_data/train/train_cleaned.csv"
label_csv = "/home/public/mkamal/dataset/filtered_data/reports_label.csv"

labels_df = pd.read_csv(label_csv)
labels_df = labels_df.set_index("path_no_ext")



report_df.head()

,path_to_png,path_no_ext,deid_patient_id,patient_report_date_order,split,frontal_lateral,ap_pa,clinical_history,section_impression_gen,section_findings_gen,report_gen
0,train/patient42142/study5/view1_frontal.png,train/patient42142/study5/view1_frontal,patient42142,5,train,Frontal,AP,"61 years female, icu patient",tracheostomy tube remains in place. right picc...,NaN,tracheostomy tube remains in place. right picc...
1,train/patient42142/study8/view1_frontal.png,train/patient42142/study8/view1_frontal,patient42142,8,train,Frontal,AP,"61 years female, tracheostomy.",tracheostomy and subdiaphragmatic enteric tube...,NaN,tracheostomy and subdiaphragmatic enteric tube...
2,train/patient42142/study2/view1_frontal.png,train/patient42142/study2/view1_frontal,patient42142,2,train,Frontal,AP,"61 years female, critical care follow-up",single portable semiupright ap view of the che...,NaN,single portable semiupright ap view of the che...
3,train/patient42142/study4/view1_frontal.png,train/patient42142/study4/view1_frontal,patient42142,4,train,Frontal,AP,icu protocol. follow up.,patchy subsegmental bibasilar (left greater th...,NaN,patchy subsegmental bibasilar (left greater th...
4,train/patient42142/study3/view1_frontal.png,train/patient42142/study3/view1_frontal,patient42142,3,train,Frontal,AP,61 years female upright please. icu protocol,upright frontal view of the chest demonstrates...,NaN,upright frontal view of the chest demonstrates...

In [5]:
labels_df.head()

,path_to_image,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,No Finding
path_no_ext,,,,,,,,,,,,,,,
train/patient42142/study5/view1_frontal,train/patient42142/study5/view1_frontal.jpg,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1.0,NaN
train/patient42142/study8/view1_frontal,train/patient42142/study8/view1_frontal.jpg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,1.0,NaN
train/patient42142/study2/view1_frontal,train/patient42142/study2/view1_frontal.jpg,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0,NaN
train/patient42142/study4/view1_frontal,train/patient42142/study4/view1_frontal.jpg,NaN,0.0,NaN,NaN,NaN,-1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN
train/patient42142/study3/view1_frontal,train/patient42142/study3/view1_frontal.jpg,NaN,NaN,NaN,NaN,0.0,0.0,NaN,1.0,NaN,0.0,NaN,NaN,1.0,NaN

In [29]:


from utils.metrics import reorder_labels_df, CHEXBERT_LABELS

labels_df = reorder_labels_df(label_csv);labels_df = labels_df.set_index("path_no_ext")
report_df = pd.read_csv(df_reports)

labels_df.head()

,path_to_image,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,No Finding
path_no_ext,,,,,,,,,,,,,,,
train/patient42142/study5/view1_frontal,train/patient42142/study5/view1_frontal.jpg,0,0,2,0,0,0,0,0,2,2,0,0,1,0
train/patient42142/study8/view1_frontal,train/patient42142/study8/view1_frontal.jpg,0,0,0,0,0,0,0,1,2,0,0,0,1,0
train/patient42142/study2/view1_frontal,train/patient42142/study2/view1_frontal.jpg,0,0,1,0,0,0,0,1,0,1,0,0,1,0
train/patient42142/study4/view1_frontal,train/patient42142/study4/view1_frontal.jpg,0,2,0,0,0,3,0,1,0,0,0,0,1,0
train/patient42142/study3/view1_frontal,train/patient42142/study3/view1_frontal.jpg,0,0,0,0,2,2,0,1,0,2,0,0,1,0

In [30]:
findings_label_path = "/home/public/mkamal/dataset/filtered_data/finding_labels.csv"
impression_label_path = "/home/public/mkamal/dataset/filtered_data/impression_labels.csv"
reports_label_path = "/home/public/mkamal/dataset/filtered_data/reports_label.csv"
reports_csv_file =  "/home/public/mkamal/dataset/filtered_data/train/train_cleaned.csv"

import pandas as pd
import numpy as np
reports_df = pd.read_csv(reports_csv_file)

def reorder_labels_df(path: str) -> pd.DataFrame:
    labels_df = pd.read_csv(path)
    CHEXBERT_LABELS = [
        "Enlarged Cardiomediastinum", "Cardiomegaly", "Lung Opacity",
        "Lung Lesion", "Edema", "Consolidation", "Pneumonia", "Atelectasis",
        "Pneumothorax", "Pleural Effusion", "Pleural Other", "Fracture",
        "Support Devices", "No Finding",
    ]
    mapping = {
        np.nan: 0,   # NaN -> 0
        1.0: 1,      # 1.0 -> 1
        0.0: 0,      # 0.0 -> 2
        -1.0: 0      # -1.0 -> 3

    }
    for col in CHEXBERT_LABELS:
        labels_df[col] = labels_df[col].map(mapping)
    # Since map does not directly handle NaN keys well, fix NaNs separately
    for col in CHEXBERT_LABELS:
        labels_df[col] = labels_df[col].fillna(0).astype(int)

    return labels_df

label_df = reorder_labels_df(reports_label_path)

label_df.head()

,path_to_image,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices,No Finding,path_no_ext
0,train/patient42142/study5/view1_frontal.jpg,0,0,0,0,0,0,0,0,0,0,0,0,1,0,train/patient42142/study5/view1_frontal
1,train/patient42142/study8/view1_frontal.jpg,0,0,0,0,0,0,0,1,0,0,0,0,1,0,train/patient42142/study8/view1_frontal
2,train/patient42142/study2/view1_frontal.jpg,0,0,1,0,0,0,0,1,0,1,0,0,1,0,train/patient42142/study2/view1_frontal
3,train/patient42142/study4/view1_frontal.jpg,0,0,0,0,0,0,0,1,0,0,0,0,1,0,train/patient42142/study4/view1_frontal
4,train/patient42142/study3/view1_frontal.jpg,0,0,0,0,0,0,0,1,0,0,0,0,1,0,train/patient42142/study3/view1_frontal